using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Blobcheg.CodeGen
{
    /// <summary>
    /// Дописывает партиал базы по <c>[Blobcheg(typeof(IДомен))]</c>. Генератор выпускает ТОЛЬКО
    /// структуру: ScriptableObject он выпускать не может — у типа из кодогена нет MonoScript, и
    /// ассетом такой тип не станет.
    /// </summary>
    [Generator]
    public sealed class BlobchegGenerator : IIncrementalGenerator
    {
        const string AttributeName = "Blobcheg.BlobchegAttribute";

        static readonly DiagnosticDescriptor NotPartial = new DiagnosticDescriptor(
            "BCHG001", "База обязана быть partial",
            "Структура '{0}' помечена [Blobcheg], но не объявлена partial — дописать в неё нечего",
            "Blobcheg", DiagnosticSeverity.Error, true);

        static readonly DiagnosticDescriptor Nested = new DiagnosticDescriptor(
            "BCHG002", "База не может быть вложенным типом",
            "Структура '{0}' помечена [Blobcheg], но вложена в другой тип — вынеси её наружу",
            "Blobcheg", DiagnosticSeverity.Error, true);

        static readonly DiagnosticDescriptor BadDomain = new DiagnosticDescriptor(
            "BCHG003", "Домен обязан быть интерфейсом-маркером",
            "В [Blobcheg] у структуры '{0}' передан '{1}' — домен объявляется интерфейсом",
            "Blobcheg", DiagnosticSeverity.Error, true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var bases = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttributeName,
                static (node, _) => node is StructDeclarationSyntax,
                static (ctx, _) => ctx);

            context.RegisterSourceOutput(bases, static (source, ctx) =>
            {
                var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var declaration = (StructDeclarationSyntax)ctx.TargetNode;

                if (!declaration.Modifiers.Any(m => m.ValueText == "partial"))
                {
                    source.ReportDiagnostic(Diagnostic.Create(NotPartial, declaration.Identifier.GetLocation(), symbol.Name));
                    return;
                }

                if (symbol.ContainingType != null)
                {
                    source.ReportDiagnostic(Diagnostic.Create(Nested, declaration.Identifier.GetLocation(), symbol.Name));
                    return;
                }

                var attribute = ctx.Attributes[0];
                if (attribute.ConstructorArguments.Length != 1
                    || !(attribute.ConstructorArguments[0].Value is INamedTypeSymbol domain))
                    return;

                if (domain.TypeKind != TypeKind.Interface)
                {
                    source.ReportDiagnostic(Diagnostic.Create(
                        BadDomain, declaration.Identifier.GetLocation(), symbol.Name, domain.Name));
                    return;
                }

                source.AddSource(symbol.Name + ".blobcheg.g.cs",
                    SourceText.From(Emit(symbol, domain), Encoding.UTF8));
            });
        }

        static string Emit(INamedTypeSymbol database, INamedTypeSymbol domain)
        {
            var text = new StringBuilder();
            var domainFull = domain.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var space = database.ContainingNamespace.IsGlobalNamespace
                ? null
                : database.ContainingNamespace.ToDisplayString();

            text.AppendLine("// <auto-generated/> Blobcheg");
            text.AppendLine("#pragma warning disable");

            if (space != null)
            {
                text.Append("namespace ").AppendLine(space);
                text.AppendLine("{");
            }

            // Без unsafe: тип с указателем внутри держится полем и в безопасном коде, а требовать
            // от потребителя allowUnsafeCode ради объявления базы незачем.
            text.Append("    ").Append(Access(database)).Append(" partial struct ")
                .Append(database.Name).AppendLine(" : global::System.IDisposable");
            text.AppendLine("    {");
            text.Append("        public const string DomainName = \"").Append(domain.Name).AppendLine("\";");
            text.AppendLine();
            text.AppendLine("        global::Blobcheg.BlobchegBlob __blob;");
            text.AppendLine();
            text.Append("        public ").Append(database.Name).AppendLine("(global::Blobcheg.BlobchegBuffer buffer)");
            text.AppendLine("        {");
            text.AppendLine("            __blob = new global::Blobcheg.BlobchegBlob(buffer, DomainName);");
            text.AppendLine("        }");
            text.AppendLine();
            text.AppendLine("        /// <summary>Имя файла базы — его же спрашивает транспорт.</summary>");
            text.AppendLine("        public static string FileName => global::Blobcheg.BlobchegNaming.FileName(DomainName);");
            text.AppendLine();
            text.AppendLine("        public bool IsCreated => __blob.IsCreated;");
            text.AppendLine();
            text.AppendLine("        public int Length => __blob.Length;");
            text.AppendLine();
            text.AppendLine("        /// <summary>Чужой домен здесь не компилируется — это единственная проверка, работающая всегда.</summary>");
            text.AppendLine("        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            text.Append("        public ref readonly T Read<T>(uint offset) where T : unmanaged, ")
                .Append(domainFull).AppendLine();
            text.AppendLine("            => ref __blob.Read<T>(offset);");
            text.AppendLine();
            text.AppendLine("        public void Dispose() => __blob.Dispose();");
            text.AppendLine("    }");

            if (space != null)
                text.AppendLine("}");

            return text.ToString();
        }

        static string Access(INamedTypeSymbol symbol)
            => symbol.DeclaredAccessibility == Accessibility.Public ? "public" : "internal";
    }
}
